import { ROLES } from "./roles";

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "dashboard.view",

  // Institution
  INSTITUTION_VIEW: "institution.view",
  INSTITUTION_MANAGE: "institution.manage",

  // Departments
  DEPARTMENTS_VIEW: "departments.view",
  DEPARTMENTS_MANAGE: "departments.manage",

  // Criteria
  CRITERIA_VIEW: "criteria.view",
  CRITERIA_MANAGE: "criteria.manage",

  // Documents
  DOCUMENTS_VIEW: "documents.view",
  DOCUMENTS_UPLOAD: "documents.upload",
  DOCUMENTS_MANAGE: "documents.manage",

  // Submissions
  SUBMISSIONS_VIEW: "submissions.view",
  SUBMISSIONS_CREATE: "submissions.create",
  SUBMISSIONS_SUBMIT: "submissions.submit",
  SUBMISSIONS_MANAGE: "submissions.manage",

  // Reviews
  REVIEWS_VIEW: "reviews.view",
  REVIEWS_ASSIGN: "reviews.assign",
  REVIEWS_APPROVE: "reviews.approve",
  REVIEWS_REJECT: "reviews.reject",
  REVIEWS_REQUEST_CHANGES: "reviews.request_changes",

  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_GENERATE: "reports.generate",

  // Users
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",
  USERS_DELETE: "users.delete",

  // Roles & System
  ROLES_VIEW: "roles.view",
  ROLES_MANAGE: "roles.manage",
  SETTINGS_MANAGE: "settings.manage",

  // Notifications
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_MANAGE: "notifications.manage",
};

// Development/Fallback permission map when backend permissions are unavailable
export const ROLE_FALLBACK_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.COORDINATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.CRITERIA_VIEW,
    PERMISSIONS.CRITERIA_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.SUBMISSIONS_CREATE,
    PERMISSIONS.SUBMISSIONS_SUBMIT,
    PERMISSIONS.SUBMISSIONS_MANAGE,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.REVIEWS_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
  ],

  [ROLES.COMMITTEE_MEMBER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CRITERIA_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.SUBMISSIONS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  [ROLES.DEPT_COORDINATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.CRITERIA_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.SUBMISSIONS_CREATE,
    PERMISSIONS.SUBMISSIONS_SUBMIT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  [ROLES.REVIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.REVIEWS_APPROVE,
    PERMISSIONS.REVIEWS_REJECT,
    PERMISSIONS.REVIEWS_REQUEST_CHANGES,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  [ROLES.DATA_APPROVER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.REVIEWS_APPROVE,
    PERMISSIONS.REVIEWS_REJECT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],

  [ROLES.PRINCIPAL_DIRECTOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INSTITUTION_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.CRITERIA_VIEW,
    PERMISSIONS.SUBMISSIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};
